name: campuspulse_mobile
description: CampusPulse Mobile App - AI-powered athletic performance tracking
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  tflite_flutter: ^0.10.4
  permission_handler: ^11.0.1
  sqflite: ^2.3.0
  path: ^1.8.3
  dio: ^5.3.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  lottie: ^2.6.0
  image: ^4.1.3
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/lottie/